networks:
  laravel_auth_sso:
  supervisor_admin_website_laravel_supervisor_admin_sso:
    external: true

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8081:80
      # - 443:443
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - redis
    container_name: laravel_auth_sso_server
    networks:
      - laravel_auth_sso
      - supervisor_admin_website_laravel_supervisor_admin_sso
    # extra_hosts:
    #  - "host.docker.internal:host-gateway"
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php_laravel_auth_sso
    networks:
      - laravel_auth_sso
      - supervisor_admin_website_laravel_supervisor_admin_sso
  redis:
    image: redis:alpine
    container_name: redis_laravel_auth_sso
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel_auth_sso
    command: redis-server --appendonly yes --replica-read-only no

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel_auth_sso
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
      #depends_on:
    networks:
      - laravel_auth_sso
  scheduler:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: scheduler_laravel_auth_sso
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan", "schedule:work" ]
    networks:
      - laravel_auth_sso
  npm:
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_auth_sso

