
networks:
  laravel_database_sso:

services:
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: mysql_laravel_database_sso
    env_file:
      - mysql/.env
    ports:
      - 3306:3306
    networks:
      - laravel_database_sso
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin_laravel_database_sso
    depends_on:
      - mysql
    ports:
      - '8891:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - laravel_database_sso

